"""planned meals and nullable winning meal

Revision ID: 7bc7fc9bf457
Revises: 9e3c05d82f2e
Create Date: 2026-06-04 15:51:31.854202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc7fc9bf457'
down_revision: Union[str, Sequence[str], None] = '9e3c05d82f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.alter_column('winning_meal_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.alter_column('winning_meal_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('planned_meals')
    # ### end Alembic commands ###
